[package]
name = "recovery_circuit"
type = "bin"
authors = ["Anoy Roy Chowdhury"]
compiler_version = ">=0.19.4"

[dependencies]
ecrecover = { tag = "v0.19.0", git = "https://github.com/colinnielsen/ecrecover-noir" }